/*
  Read data from analog input scale it and display on Neopixel
  after suitable processing (FFT, FHT, FIR filter or simple round
  robin of amplitudes)
*/
#include <Adafruit_NeoPixel.h>


#define PIN 6 // digital pin for programming neopixels
#define NUM_PIXELS 32 // this is the size of my neopixel strip           

Adafruit_NeoPixel strip = Adafruit_NeoPixel(NUM_PIXELS, PIN, NEO_GRB + NEO_KHZ800);

int16_t  capture[NUM_PIXELS];    // Audio capture buffer
volatile uint32_t samplePos = 0;     // Buffer position counter

// This is the mapping from the values in the buckets to the colors representing those values. These numbers were generated by some C code that I've pasted into the bottom of this
// file. The colors go from blue->green->red with an increase in intensity as the values increase. There's also a log10 based response curve figured in.
#define NUM_COLORS 64
static const uint32_t PROGMEM colors[NUM_COLORS] = { 
0x42, 0x1c37, 0x332e, 0x4823, 0x5b1a, 0x6c11, 0x7c08, 0x8c00, 0x88900, 0x108600, 0x178300, 0x1e8100, 0x267e00, 0x2d7b00, 0x347700, 0x3a7400, 0x407100, 0x466e00, 0x4d6b00, 0x526800, 0x586500, 0x5e6200, 0x636000, 0x685d00, 0x6d5a00, 0x725700, 0x775400, 0x7c5100, 0x804f00, 0x864c00, 0x8a4900, 0x8f4600, 0x924400, 0x974100, 0x9b3f00, 0x9f3c00, 0xa33a00, 0xa83700, 0xab3500, 0xaf3200, 0xb33000, 0xb72e00, 0xbb2b00, 0xbe2900, 0xc12700, 0xc52400, 0xc92200, 0xcc2000, 0xd01e00, 0xd31c00, 0xd71900, 0xda1700, 0xdc1500, 0xe01300, 0xe31100, 0xe60f00, 0xe90d00, 0xec0b00, 0xf00800, 0xf30600, 0xf60400, 0xf90200, 0xfc0000, 0xff0000
};

// the setup routine runs once when you press reset:
void setup() {
  // initialize serial communication at 9600 bits per second:
  Serial.begin(115200);
  // Neopixels setup
  // Initialize all pixels to 'off'
  strip.setBrightness(255);
  strip.begin(); // Initialize all pixels to 'off'
  cli();         // disable interrupts when writing neopixels   
  strip.show();
  sei();         // Enable interrupts
}

// the loop routine runs over and over again forever:
void loop() {
  // read the input on analog pin 0:
  int sensorValue = analogRead(A0);
  capture[samplePos] = abs(sensorValue-512);
  samplePos++;
  samplePos%=NUM_PIXELS;
  for (int i = 0; i < strip.numPixels(); i++)
  {
     int value = capture[i]-448;
     if(value>=0)
     {
        Serial.println(value);
        strip.setPixelColor(i, pgm_read_dword(&colors[value]));
     }
     else
     {
        strip.setPixelColor(i, 0x0);
     }
     
     
  }
  cli();        // no interrupts while writing the neopixels
  strip.show();
  sei();        // restore interrupts
  delay(1);        // delay in between reads for stability
}

